<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE peliculas [
    <!ELEMENT peliculas (pelicula)+>
    <!ELEMENT pelicula (titulo, director, autor*)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT director (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
]>

<!-- Falta elemento raíz -->
<peliculas>
    <pelicula>
        <titulo>Con faldas y a lo loco</titulo>
        <director>Billy Wilder</director>
    </pelicula>
    <pelicula>
        <titulo>Sopa de ganso</titulo>
        <director>Leo McCarey</director> <!-- Las etiquetas deben seguir el mismo orden -->
        <autor>barto</autor> <!-- Etiqueta autor mal abierta --> <!-- Autor fuera de película -->
    </pelicula>
</peliculas>